"""Remove lastAttendance from Employe

Revision ID: cf5024ce832f
Revises: 968edb497418
Create Date: 2024-05-01 06:27:40.536180

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cf5024ce832f'
down_revision = '968edb497418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employe', schema=None) as batch_op:
        batch_op.drop_column('lastAttendance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastAttendance', mysql.DATETIME(), nullable=False))

    # ### end Alembic commands ###
